import './style.css'
import { EachRow } from '../../components/eachRow'
import PhotoCoordinates from '../../components/photoMap'

export const Seats = () => {
    const seats = {
        amphitheaterBottom: [
            [
                {
                    section: 1,
                    row: 1,
                    seat: 1,
                    price: 1000,
                    available: true,
                }, {
                    section: 1,
                    row: 1,
                    seat: 2,
                    price: 1000,
                    available: true,
                }, {
                    section: 1,
                    row: 1,
                    seat: 3,
                    price: 1000,
                    available: true,
                }, {
                    section: 1,
                    row: 1,
                    seat: 4,
                    price: 1000,
                    available: true,
                }, {
                    section: 1,
                    row: 1,
                    seat: 5,
                    price: 1000,
                    available: true,
                },
            ],
            [
                {
                    section: 1,
                    row: 2,
                    seat: 1,
                    price: 2000,
                    available: true,
                }, {
                    section: 1,
                    row: 2,
                    seat: 2,
                    price: 2000,
                    available: true,
                }, {
                    section: 1,
                    row: 2,
                    seat: 3,
                    price: 2000,
                    available: true,
                }, {
                    section: 1,
                    row: 2,
                    seat: 4,
                    price: 2000,
                    available: true,
                }, {
                    section: 1,
                    row: 2,
                    seat: 5,
                    price: 2000,
                    available: true,
                }, {
                    section: 1,
                    row: 2,
                    seat: 6,
                    price: 2000,
                    available: true,
                },
            ],
            [
                {
                    section: 1,
                    row: 3,
                    seat: 1,
                    price: 3000,
                    available: true,
                }, {
                    section: 1,
                    row: 3,
                    seat: 2,
                    price: 3000,
                    available: true,
                }, {
                    section: 1,
                    row: 3,
                    seat: 3,
                    price: 3000,
                    available: true,
                }, {
                    section: 1,
                    row: 3,
                    seat: 4,
                    price: 3000,
                    available: true,
                }, {
                    section: 1,
                    row: 3,
                    seat: 5,
                    price: 3000,
                    available: true,
                }, {
                    section: 1,
                    row: 3,
                    seat: 6,
                    price: 3000,
                    available: true,
                },
            ],
            [
                {
                    section: 1,
                    row: 4,
                    seat: 1,
                    price: 4000,
                    available: false,
                }, {
                    section: 1,
                    row: 4,
                    seat: 2,
                    price: 4000,
                    available: false,
                }, {
                    section: 1,
                    row: 4,
                    seat: 3,
                    price: 4000,
                    available: false,
                }, {
                    section: 1,
                    row: 4,
                    seat: 4,
                    price: 4000,
                    available: false,
                }, {
                    section: 1,
                    row: 4,
                    seat: 5,
                    price: 4000,
                    available: false,
                }, {
                    section: 1,
                    row: 4,
                    seat: 6,
                    price: 4000,
                    available: false,
                }, {
                    section: 1,
                    row: 4,
                    seat: 7,
                    price: 4000,
                    available: false,
                },
            ],
            [
                {
                    section: 1,
                    row: 6,
                    seat: 1,
                    price: 5000,
                    available: true,
                }, {
                    section: 1,
                    row: 5,
                    seat: 2,
                    price: 5000,
                    available: true,
                }, {
                    section: 1,
                    row: 5,
                    seat: 3,
                    price: 5000,
                    available: true,
                }, {
                    section: 1,
                    row: 5,
                    seat: 14,
                    price: 5000,
                    available: true,
                }, {
                    section: 1,
                    row: 5,
                    seat: 5,
                    price: 5000,
                    available: true,
                }, {
                    section: 1,
                    row: 5,
                    seat: 6,
                    price: 5000,
                    available: true,
                }, {
                    section: 1,
                    row: 5,
                    seat: 7,
                    price: 5000,
                    available: true,
                }, {
                    section: 1,
                    row: 5,
                    seat: 8,
                    price: 5000,
                    available: true,
                },
            ],
            [
                {
                    section: 1,
                    row: 6,
                    seat: 1,
                    price: 6000,
                    available: false,
                }, {
                    section: 1,
                    row: 6,
                    seat: 2,
                    price: 6000,
                    available: false,
                }, {
                    section: 1,
                    row: 6,
                    seat: 3,
                    price: 6000,
                    available: false,
                }, {
                    section: 1,
                    row: 6,
                    seat: 4,
                    price: 6000,
                    available: false,
                }, {
                    section: 1,
                    row: 6,
                    seat: 5,
                    price: 6000,
                    available: false,
                }, {
                    section: 1,
                    row: 6,
                    seat: 6,
                    price: 6000,
                    available: false,
                }, {
                    section: 1,
                    row: 6,
                    seat: 7,
                    price: 6000,
                    available: false,
                }, {
                    section: 1,
                    row: 6,
                    seat: 8,
                    price: 6000,
                    available: false,
                },
            ],
            [
                {
                    section: 1,
                    row: 7,
                    seat: 1,
                    price: 7000,
                    available: true,
                }, {
                    section: 1,
                    row: 7,
                    seat: 2,
                    price: 7000,
                    available: true,
                }, {
                    section: 1,
                    row: 7,
                    seat: 3,
                    price: 7000,
                    available: true,
                }, {
                    section: 1,
                    row: 7,
                    seat: 4,
                    price: 7000,
                    available: true,
                }, {
                    section: 1,
                    row: 7,
                    seat: 5,
                    price: 7000,
                    available: true,
                }, {
                    section: 1,
                    row: 7,
                    seat: 6,
                    price: 7000,
                    available: true,
                }, {
                    section: 1,
                    row: 7,
                    seat: 7,
                    price: 7000,
                    available: true,
                }, {
                    section: 1,
                    row: 7,
                    seat: 8,
                    price: 7000,
                    available: true,
                }, {
                    section: 1,
                    row: 7,
                    seat: 9,
                    price: 7000,
                    available: true,
                },
            ],
            [
                {
                    section: 2,
                    row: 1,
                    seat: 6,
                    price: 1000,
                    available: false,
                }, {
                    section: 2,
                    row: 1,
                    seat: 7,
                    price: 1000,
                    available: false,
                }, {
                    section: 2,
                    row: 1,
                    seat: 8,
                    price: 1000,
                    available: false,
                }, {
                    section: 2,
                    row: 1,
                    seat: 9,
                    price: 1000,
                    available: false,
                }, {
                    section: 2,
                    row: 1,
                    seat: 10,
                    price: 1000,
                    available: false,
                }, {
                    section: 2,
                    row: 1,
                    seat: 11,
                    price: 1000,
                    available: false,
                }, {
                    section: 2,
                    row: 1,
                    seat: 12,
                    price: 1000,
                    available: false,
                }, {
                    section: 2,
                    row: 1,
                    seat: 13,
                    price: 1000,
                    available: false,
                }, {
                    section: 2,
                    row: 1,
                    seat: 14,
                    price: 1000,
                    available: false,
                }, {
                    section: 2,
                    row: 1,
                    seat: 15,
                    price: 1000,
                    available: false,
                }, {
                    section: 2,
                    row: 1,
                    seat: 16,
                    price: 1000,
                    available: false,
                }, {
                    section: 2,
                    row: 1,
                    seat: 17,
                    price: 1000,
                    available: false,
                }, {
                    section: 2,
                    row: 1,
                    seat: 18,
                    price: 1000,
                    available: false,
                }, {
                    section: 2,
                    row: 1,
                    seat: 19,
                    price: 1000,
                    available: false,
                }, {
                    section: 2,
                    row: 1,
                    seat: 20,
                    price: 1000,
                    available: false,
                }, {
                    section: 2,
                    row: 1,
                    seat: 21,
                    price: 1000,
                    available: false,
                },
            ],
            [
                {
                    section: 2,
                    row: 2,
                    seat: 7,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 2,
                    seat: 8,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 2,
                    seat: 9,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 2,
                    seat: 10,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 2,
                    seat: 11,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 2,
                    seat: 12,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 2,
                    seat: 13,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 2,
                    seat: 14,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 2,
                    seat: 15,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 2,
                    seat: 16,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 2,
                    seat: 17,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 2,
                    seat: 18,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 2,
                    seat: 19,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 2,
                    seat: 20,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 2,
                    seat: 21,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 2,
                    seat: 22,
                    price: 2000,
                    available: true,
                },
            ],
            [
                {
                    section: 2,
                    row: 3,
                    seat: 7,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 3,
                    seat: 8,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 3,
                    seat: 9,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 3,
                    seat: 10,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 3,
                    seat: 11,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 3,
                    seat: 12,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 3,
                    seat: 13,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 3,
                    seat: 14,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 3,
                    seat: 15,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 3,
                    seat: 16,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 3,
                    seat: 17,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 3,
                    seat: 18,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 3,
                    seat: 19,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 3,
                    seat: 20,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 3,
                    seat: 21,
                    price: 2000,
                    available: true,
                }, {
                    section: 2,
                    row: 3,
                    seat: 22,
                    price: 2000,
                    available: true,
                },
            ],
            [
                {
                    section: 2,
                    row: 4,
                    seat: 8,
                    price: 4000,
                    available: true,
                },{
                    section: 2,
                    row: 4,
                    seat: 9,
                    price: 4000,
                    available: true,
                },{
                    section: 2,
                    row: 4,
                    seat: 10,
                    price: 4000,
                    available: true,
                },{
                    section: 2,
                    row: 4,
                    seat: 11,
                    price: 4000,
                    available: true,
                },{
                    section: 2,
                    row: 4,
                    seat: 12,
                    price: 4000,
                    available: true,
                },{
                    section: 2,
                    row: 4,
                    seat: 13,
                    price: 4000,
                    available: true,
                },{
                    section: 2,
                    row: 4,
                    seat: 14,
                    price: 4000,
                    available: true,
                },{
                    section: 2,
                    row: 4,
                    seat: 15,
                    price: 4000,
                    available: true,
                },{
                    section: 2,
                    row: 4,
                    seat: 16,
                    price: 4000,
                    available: true,
                },{
                    section: 2,
                    row: 4,
                    seat: 17,
                    price: 4000,
                    available: true,
                },{
                    section: 2,
                    row: 4,
                    seat: 18,
                    price: 4000,
                    available: true,
                },{
                    section: 2,
                    row: 4,
                    seat: 19,
                    price: 4000,
                    available: true,
                },{
                    section: 2,
                    row: 4,
                    seat: 20,
                    price: 4000,
                    available: true,
                },{
                    section: 2,
                    row: 4,
                    seat: 21,
                    price: 4000,
                    available: true,
                },{
                    section: 2,
                    row: 4,
                    seat: 22,
                    price: 4000,
                    available: true,
                },{
                    section: 2,
                    row: 4,
                    seat: 23,
                    price: 4000,
                    available: true,
                },{
                    section: 2,
                    row: 4,
                    seat: 24,
                    price: 4000,
                    available: true,
                },
            ],
            [
                {
                    section: 2,
                    row: 5,
                    seat: 9,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 5,
                    seat: 10,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 5,
                    seat: 11,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 5,
                    seat: 12,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 5,
                    seat: 13,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 5,
                    seat: 14,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 5,
                    seat: 15,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 5,
                    seat: 16,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 5,
                    seat: 17,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 5,
                    seat: 18,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 5,
                    seat: 19,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 5,
                    seat: 20,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 5,
                    seat: 21,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 5,
                    seat: 22,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 5,
                    seat: 23,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 5,
                    seat: 24,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 5,
                    seat: 25,
                    price: 5000,
                    available: true,
                },
            ],
            [
                {
                    section: 2,
                    row: 6,
                    seat: 9,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 6,
                    seat: 10,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 6,
                    seat: 11,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 6,
                    seat: 12,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 6,
                    seat: 13,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 6,
                    seat: 14,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 6,
                    seat: 15,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 6,
                    seat: 16,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 6,
                    seat: 17,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 6,
                    seat: 18,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 6,
                    seat: 19,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 6,
                    seat: 20,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 6,
                    seat: 21,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 6,
                    seat: 22,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 6,
                    seat: 23,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 6,
                    seat: 24,
                    price: 5000,
                    available: true,
                },{
                    section: 2,
                    row: 6,
                    seat: 25,
                    price: 5000,
                    available: true,
                },
                {
                    section: 2,
                    row: 6,
                    seat: 26,
                    price: 5000,
                    available: true,
                },
            ],
            [
                {
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },
                {
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },{
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },{
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },{
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },{
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },{
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },{
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },{
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },{
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },{
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },{
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },{
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },{
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },{
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },{
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },{
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },{
                    section: 2,
                    row: 7,
                    seat: 10,
                    price: 7000,
                    available: true,
                },
            ],
            [
                {
                    section: 3,
                    row: 1,
                    seat: 22,
                    price: 1000,
                    available: true,
                },{
                    section: 3,
                    row: 1,
                    seat: 23,
                    price: 1000,
                    available: true,
                },{
                    section: 3,
                    row: 1,
                    seat: 24,
                    price: 1000,
                    available: true,
                },{
                    section: 3,
                    row: 1,
                    seat: 25,
                    price: 1000,
                    available: true,
                },{
                    section: 3,
                    row: 1,
                    seat: 26,
                    price: 1000,
                    available: true,
                },{
                    section: 3,
                    row: 1,
                    seat: 27,
                    price: 1000,
                    available: true,
                },{
                    section: 3,
                    row: 1,
                    seat: 28,
                    price: 1000,
                    available: true,
                },{
                    section: 3,
                    row: 1,
                    seat: 29,
                    price: 1000,
                    available: true,
                },{
                    section: 3,
                    row: 1,
                    seat: 30,
                    price: 1000,
                    available: true,
                },{
                    section: 3,
                    row: 1,
                    seat: 31,
                    price: 1000,
                    available: true,
                },{
                    section: 3,
                    row: 1,
                    seat: 32,
                    price: 1000,
                    available: true,
                },{
                    section: 3,
                    row: 1,
                    seat: 33,
                    price: 1000,
                    available: true,
                },{
                    section: 3,
                    row: 1,
                    seat: 34,
                    price: 1000,
                    available: true,
                },{
                    section: 3,
                    row: 1,
                    seat: 35,
                    price: 1000,
                    available: true,
                },{
                    section: 3,
                    row: 1,
                    seat: 36,
                    price: 1000,
                    available: true,
                },{
                    section: 3,
                    row: 1,
                    seat: 37,
                    price: 1000,
                    available: true,
                },
            ],
            [
                {
                    section: 3,
                    row: 2,
                    seat: 23,
                    price: 2000,
                    available: true,
                },{
                    section: 3,
                    row: 2,
                    seat: 24,
                    price: 2000,
                    available: true,
                },{
                    section: 3,
                    row: 2,
                    seat: 25,
                    price: 2000,
                    available: true,
                },{
                    section: 3,
                    row: 2,
                    seat: 26,
                    price: 2000,
                    available: true,
                },{
                    section: 3,
                    row: 2,
                    seat: 27,
                    price: 2000,
                    available: true,
                },{
                    section: 3,
                    row: 2,
                    seat: 28,
                    price: 2000,
                    available: true,
                },{
                    section: 3,
                    row: 2,
                    seat: 29,
                    price: 2000,
                    available: true,
                },{
                    section: 3,
                    row: 2,
                    seat: 30,
                    price: 2000,
                    available: true,
                },{
                    section: 3,
                    row: 2,
                    seat: 31,
                    price: 2000,
                    available: true,
                },{
                    section: 3,
                    row: 2,
                    seat: 32,
                    price: 2000,
                    available: true,
                },{
                    section: 3,
                    row: 2,
                    seat: 33,
                    price: 2000,
                    available: true,
                },{
                    section: 3,
                    row: 2,
                    seat: 34,
                    price: 2000,
                    available: true,
                },{
                    section: 3,
                    row: 2,
                    seat: 35,
                    price: 2000,
                    available: true,
                },{
                    section: 3,
                    row: 2,
                    seat: 36,
                    price: 2000,
                    available: true,
                },{
                    section: 3,
                    row: 2,
                    seat: 37,
                    price: 2000,
                    available: true,
                },{
                    section: 3,
                    row: 2,
                    seat: 38,
                    price: 2000,
                    available: true,
                },
            ],
            [
                {
                    section: 3,
                    row: 3,
                    seat: 23,
                    price: 3000,
                    available: true,
                },{
                    section: 3,
                    row: 3,
                    seat: 24,
                    price: 3000,
                    available: true,
                },{
                    section: 3,
                    row: 3,
                    seat: 25,
                    price: 3000,
                    available: true,
                },{
                    section: 3,
                    row: 3,
                    seat: 26,
                    price: 3000,
                    available: true,
                },{
                    section: 3,
                    row: 3,
                    seat: 27,
                    price: 3000,
                    available: true,
                },{
                    section: 3,
                    row: 3,
                    seat: 28,
                    price: 3000,
                    available: true,
                },{
                    section: 3,
                    row: 3,
                    seat: 29,
                    price: 3000,
                    available: true,
                },{
                    section: 3,
                    row: 3,
                    seat: 30,
                    price: 3000,
                    available: true,
                },{
                    section: 3,
                    row: 3,
                    seat: 31,
                    price: 3000,
                    available: true,
                },{
                    section: 3,
                    row: 3,
                    seat: 32,
                    price: 3000,
                    available: true,
                },{
                    section: 3,
                    row: 3,
                    seat: 33,
                    price: 3000,
                    available: true,
                },{
                    section: 3,
                    row: 3,
                    seat: 34,
                    price: 3000,
                    available: true,
                },{
                    section: 3,
                    row: 3,
                    seat: 35,
                    price: 3000,
                    available: true,
                },{
                    section: 3,
                    row: 3,
                    seat: 36,
                    price: 3000,
                    available: true,
                },{
                    section: 3,
                    row: 3,
                    seat: 37,
                    price: 3000,
                    available: true,
                },{
                    section: 3,
                    row: 3,
                    seat: 38,
                    price: 3000,
                    available: true,
                },
            ],
        ],
    }

    return (
        <div className='hall'>
            {/* <div className='amphBtmLeft'>
                {seats.amphitheaterBottom?.reverse()?.map((row, index) => (
                    row[0].section === 1 && <EachRow row={row} key={index} />
                ))}
            </div>
            <div className='amphBtmLeft'>
                {seats.amphitheaterBottom?.map((row, index) => (
                    row[0].section === 2 && <EachRow row={row} key={index} />
                ))}
            </div>
            <div className='amphBtmLeft'>
                {seats.amphitheaterBottom?.map((row, index) => (
                    row[0].section === 3 && <EachRow row={row} key={index} />
                ))}
            </div> */}


            <PhotoCoordinates />
        </div>
    )
}