import './style.css'
import { useEffect, useState } from 'react'
import { useDispatch } from 'react-redux'
import { RemoveTicketsAction, SetTicketsAction } from '../../services/action/action'

const AramKhachatryan = ({ secion }) => {
    const dispatch = useDispatch()
    const [coordinatesState, setCoordinatesState] = useState([])
    const [activeTicket, setActiveTicket] = useState({})
    const [position, setPosition] = useState({ x: '', y: '' })
    const [showModal, setShowModal] = useState(false)
    const [activeButton, setActiveButton] = useState(null)

    // useEffect(() => {
    //     let arr = [...seansArr]
    //     secion.map((elm, index) => {
    //         arr.map((e, i) => {
    //             if (e.section === elm.section) {
    //                 e.price = elm.price
    //             }
    //         })
    //     })
    //     setSeansArr(arr)
    // }, [])

    const [seansArr, setSeansArr] = useState([
        { "id": 1247, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1231, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1213, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1195, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1175, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1162, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1141, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1120, "price": "", "row": 7, "section": 1, "seat": 1 },

        { "id": 1265, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 1253, "price": "", "row": 5, "section": 1, "seat": 2 },
        { "id": 1237, "price": "", "row": 5, "section": 1, "seat": 3 },
        { "id": 1225, "price": "", "row": 5, "section": 1, "seat": 4 },
        { "id": 1210, "price": "", "row": 5, "section": 1, "seat": 5 },
        { "id": 1197, "price": "", "row": 5, "section": 1, "seat": 6 },
        { "id": 1180, "price": "", "row": 5, "section": 1, "seat": 7 },
        { "id": 1169, "price": "", "row": 5, "section": 1, "seat": 8 },

        { "id": 1272, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1259, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1243, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1227, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1209, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1196, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1179, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1165, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1147, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1254, "price": "", "row": 4, "section": 1, "seat": 2 },

        { "id": 1266, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 1239, "price": "", "row": 4, "section": 1, "seat": 3 },
        { "id": 1228, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 1214, "price": "", "row": 4, "section": 1, "seat": 5 },
        { "id": 1201, "price": "", "row": 4, "section": 1, "seat": 6 },
        { "id": 1187, "price": "", "row": 4, "section": 1, "seat": 7 },

        { "id": 1275, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 1267, "price": "", "row": 3, "section": 1, "seat": 2 },
        { "id": 1257, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 1244, "price": "", "row": 3, "section": 1, "seat": 4 },
        { "id": 1234, "price": "", "row": 3, "section": 1, "seat": 5 },
        { "id": 1219, "price": "", "row": 3, "section": 1, "seat": 6 },
        { "id": 1207, "price": "", "row": 3, "section": 1, "seat": 7 },

        { "id": 1276, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 1270, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 1260, "price": "", "row": 2, "section": 1, "seat": 3 },
        { "id": 1249, "price": "", "row": 2, "section": 1, "seat": 4 },
        { "id": 1235, "price": "", "row": 2, "section": 1, "seat": 5 },
        { "id": 1223, "price": "", "row": 2, "section": 1, "seat": 6 },

        { "id": 1221, "price": "", "row": 1, "section": 1, "seat": 5 },
        { "id": 1215, "price": "", "row": 1, "section": 1, "seat": 6 },
        { "id": 1205, "price": "", "row": 1, "section": 1, "seat": 7 },
        { "id": 1193, "price": "", "row": 1, "section": 1, "seat": 8 },
        { "id": 1188, "price": "", "row": 1, "section": 1, "seat": 9 },
        { "id": 1180, "price": "", "row": 1, "section": 1, "seat": 10 },
        { "id": 1176, "price": "", "row": 1, "section": 1, "seat": 11 },

        { "id": 1203, "price": "", "row": 2, "section": 1, "seat": 7 },
        { "id": 1191, "price": "", "row": 2, "section": 1, "seat": 8 },
        { "id": 1182, "price": "", "row": 2, "section": 1, "seat": 9 },
        { "id": 1173, "price": "", "row": 2, "section": 1, "seat": 10 },
        { "id": 1161, "price": "", "row": 2, "section": 1, "seat": 11 },
        { "id": 1151, "price": "", "row": 2, "section": 1, "seat": 12 },
        { "id": 1137, "price": "", "row": 2, "section": 1, "seat": 13 },

        { "id": 1181, "price": "", "row": 3, "section": 1, "seat": 8 },
        { "id": 1171, "price": "", "row": 3, "section": 1, "seat": 9 },
        { "id": 1155, "price": "", "row": 3, "section": 1, "seat": 10 },
        { "id": 1143, "price": "", "row": 3, "section": 1, "seat": 11 },
        { "id": 1126, "price": "", "row": 3, "section": 1, "seat": 12 },
        { "id": 1118, "price": "", "row": 3, "section": 1, "seat": 13 },
        { "id": 1106, "price": "", "row": 3, "section": 1, "seat": 14 },

        { "id": 1157, "price": "", "row": 4, "section": 1, "seat": 8 },
        { "id": 1142, "price": "", "row": 4, "section": 1, "seat": 9 },
        { "id": 1125, "price": "", "row": 4, "section": 1, "seat": 10 },
        { "id": 1112, "price": "", "row": 4, "section": 1, "seat": 11 },
        { "id": 1112, "price": "", "row": 4, "section": 1, "seat": 12 },
        { "id": 1100, "price": "", "row": 4, "section": 1, "seat": 13 },
        { "id": 1083, "price": "", "row": 4, "section": 1, "seat": 14 },
        { "id": 1075, "price": "", "row": 4, "section": 1, "seat": 15 },

        { "id": 1128, "price": "", "row": 5, "section": 1, "seat": 9 },
        { "id": 1114, "price": "", "row": 5, "section": 1, "seat": 10 },
        { "id": 1099, "price": "", "row": 5, "section": 1, "seat": 11 },
        { "id": 1080, "price": "", "row": 5, "section": 1, "seat": 12 },
        { "id": 1069, "price": "", "row": 5, "section": 1, "seat": 13 },
        { "id": 1059, "price": "", "row": 5, "section": 1, "seat": 14 },
        { "id": 1043, "price": "", "row": 5, "section": 1, "seat": 15 },
        { "id": 1032, "price": "", "row": 5, "section": 1, "seat": 16 },

        { "id": 1107, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1091, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1073, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1061, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1039, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1026, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1017, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1001, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1079, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1065, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1051, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1031, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1016, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 995, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 986, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 972, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 957, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1025, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 1009, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 991, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 982, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 964, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 944, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 932, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 922, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 1035, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 1015, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 990, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 975, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 956, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 942, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 928, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 908, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 897, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 994, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 974, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 950, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 938, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 918, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 903, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 887, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 868, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 859, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 889, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 867, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 857, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 843, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 830, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 802, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 1166, "price": "", "row": 1, "section": 1, "seat": 12 },
        { "id": 1158, "price": "", "row": 1, "section": 1, "seat": 13 },
        { "id": 1152, "price": "", "row": 1, "section": 1, "seat": 14 },
        { "id": 1148, "price": "", "row": 1, "section": 1, "seat": 15 },
        { "id": 1138, "price": "", "row": 1, "section": 1, "seat": 16 },
        { "id": 1135, "price": "", "row": 1, "section": 1, "seat": 17 },
        { "id": 1133, "price": "", "row": 1, "section": 1, "seat": 18 },
        { "id": 1129, "price": "", "row": 1, "section": 1, "seat": 19 },

        { "id": 1121, "price": "", "row": 2, "section": 1, "seat": 14 },
        { "id": 1115, "price": "", "row": 2, "section": 1, "seat": 15 },
        { "id": 1108, "price": "", "row": 2, "section": 1, "seat": 16 },
        { "id": 1103, "price": "", "row": 2, "section": 1, "seat": 17 },
        { "id": 1097, "price": "", "row": 2, "section": 1, "seat": 18 },
        { "id": 1095, "price": "", "row": 2, "section": 1, "seat": 19 },
        { "id": 1092, "price": "", "row": 2, "section": 1, "seat": 20 },
        { "id": 1089, "price": "", "row": 2, "section": 1, "seat": 21 },
        { "id": 1085, "price": "", "row": 2, "section": 1, "seat": 22 },

        { "id": 1084, "price": "", "row": 3, "section": 1, "seat": 15 },
        { "id": 1077, "price": "", "row": 3, "section": 1, "seat": 16 },
        { "id": 1071, "price": "", "row": 3, "section": 1, "seat": 17 },
        { "id": 1066, "price": "", "row": 3, "section": 1, "seat": 18 },
        { "id": 1062, "price": "", "row": 3, "section": 1, "seat": 19 },
        { "id": 1056, "price": "", "row": 3, "section": 1, "seat": 20 },
        { "id": 1052, "price": "", "row": 3, "section": 1, "seat": 21 },
        { "id": 1049, "price": "", "row": 3, "section": 1, "seat": 22 },
        { "id": 1045, "price": "", "row": 3, "section": 1, "seat": 23 },
        { "id": 1040, "price": "", "row": 3, "section": 1, "seat": 24 },

        { "id": 1055, "price": "", "row": 4, "section": 1, "seat": 16 },
        { "id": 1044, "price": "", "row": 4, "section": 1, "seat": 17 },
        { "id": 1037, "price": "", "row": 4, "section": 1, "seat": 18 },
        { "id": 1027, "price": "", "row": 4, "section": 1, "seat": 19 },
        { "id": 1023, "price": "", "row": 4, "section": 1, "seat": 20 },
        { "id": 1018, "price": "", "row": 4, "section": 1, "seat": 21 },
        { "id": 1011, "price": "", "row": 4, "section": 1, "seat": 22 },
        { "id": 1007, "price": "", "row": 4, "section": 1, "seat": 23 },
        { "id": 1005, "price": "", "row": 4, "section": 1, "seat": 24 },
        { "id": 1002, "price": "", "row": 4, "section": 1, "seat": 25 },
        { "id": 997, "price": "", "row": 4, "section": 1, "seat": 26 },

        { "id": 1010, "price": "", "row": 5, "section": 1, "seat": 17 },
        { "id": 996, "price": "", "row": 5, "section": 1, "seat": 18 },
        { "id": 988, "price": "", "row": 5, "section": 1, "seat": 19 },
        { "id": 984, "price": "", "row": 5, "section": 1, "seat": 20 },
        { "id": 977, "price": "", "row": 5, "section": 1, "seat": 21 },
        { "id": 970, "price": "", "row": 5, "section": 1, "seat": 22 },
        { "id": 966, "price": "", "row": 5, "section": 1, "seat": 23 },
        { "id": 962, "price": "", "row": 5, "section": 1, "seat": 24 },
        { "id": 958, "price": "", "row": 5, "section": 1, "seat": 25 },
        { "id": 952, "price": "", "row": 5, "section": 1, "seat": 26 },
        { "id": 948, "price": "", "row": 5, "section": 1, "seat": 27 },

        { "id": 976, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 968, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 951, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 945, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 940, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 934, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 929, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 923, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 919, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 916, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 913, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 909, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 933, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 926, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 912, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 906, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 900, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 895, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 890, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 885, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 881, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 879, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 877, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 873, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 899, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 893, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 883, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 872, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 865, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 861, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 854, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 851, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 849, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 844, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 841, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 836, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 837, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 871, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 863, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 853, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 847, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 835, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 831, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 827, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 824, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 820, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 817, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 811, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 809, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 807, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 805, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 833, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 826, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 822, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 814, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 803, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 798, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 794, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 792, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 788, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 785, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 782, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 780, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 777, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 813, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 800, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 796, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 790, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 784, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 774, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 771, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 767, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 764, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 759, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 754, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 752, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 749, "price": "", "row": 11, "section": 1, "seat": 1 },

        { "id": 745, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 776, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 769, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 763, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 756, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 748, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 742, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 736, "price": "", "row": 12, "section": 1, "seat": 1 },

        { "id": 733, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 729, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 725, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 721, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 719, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 716, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 758, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 744, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 739, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 731, "price": "", "row": 13, "section": 1, "seat": 1 },

        { "id": 431, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 724, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 715, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 711, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 709, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 706, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 703, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 700, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 698, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 696, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 694, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 684, "price": "", "row": 14, "section": 1, "seat": 1 },
        { "id": 681, "price": "", "row": 14, "section": 1, "seat": 1 },
        { "id": 678, "price": "", "row": 14, "section": 1, "seat": 1 },

        { "id": 1130, "price": "", "row": 1, "section": 1, "seat": 20 },
        { "id": 1134, "price": "", "row": 1, "section": 1, "seat": 21 },
        { "id": 1136, "price": "", "row": 1, "section": 1, "seat": 22 },
        { "id": 1139, "price": "", "row": 1, "section": 1, "seat": 23 },
        { "id": 1149, "price": "", "row": 1, "section": 1, "seat": 24 },
        { "id": 1153, "price": "", "row": 1, "section": 1, "seat": 25 },
        { "id": 1159, "price": "", "row": 1, "section": 1, "seat": 26 },
        { "id": 1167, "price": "", "row": 1, "section": 1, "seat": 27 },

        { "id": 1086, "price": "", "row": 2, "section": 1, "seat": 23 },
        { "id": 1090, "price": "", "row": 2, "section": 1, "seat": 24 },
        { "id": 1093, "price": "", "row": 2, "section": 1, "seat": 25 },
        { "id": 1096, "price": "", "row": 2, "section": 1, "seat": 26 },
        { "id": 1098, "price": "", "row": 2, "section": 1, "seat": 27 },
        { "id": 1104, "price": "", "row": 2, "section": 1, "seat": 28 },
        { "id": 1109, "price": "", "row": 2, "section": 1, "seat": 29 },
        { "id": 1116, "price": "", "row": 2, "section": 1, "seat": 30 },
        { "id": 1122, "price": "", "row": 2, "section": 1, "seat": 31 },

        { "id": 1041, "price": "", "row": 3, "section": 1, "seat": 25 },
        { "id": 1046, "price": "", "row": 3, "section": 1, "seat": 26 },
        { "id": 1050, "price": "", "row": 3, "section": 1, "seat": 27 },
        { "id": 1053, "price": "", "row": 3, "section": 1, "seat": 28 },
        { "id": 1057, "price": "", "row": 3, "section": 1, "seat": 29 },
        { "id": 1063, "price": "", "row": 3, "section": 1, "seat": 30 },
        { "id": 1067, "price": "", "row": 3, "section": 1, "seat": 31 },
        { "id": 1072, "price": "", "row": 3, "section": 1, "seat": 32 },
        { "id": 1078, "price": "", "row": 3, "section": 1, "seat": 33 },
        { "id": 1087, "price": "", "row": 3, "section": 1, "seat": 34 },

        { "id": 998, "price": "", "row": 4, "section": 1, "seat": 27 },
        { "id": 1003, "price": "", "row": 4, "section": 1, "seat": 28 },
        { "id": 1006, "price": "", "row": 4, "section": 1, "seat": 29 },
        { "id": 1008, "price": "", "row": 4, "section": 1, "seat": 30 },
        { "id": 1012, "price": "", "row": 4, "section": 1, "seat": 31 },
        { "id": 1019, "price": "", "row": 4, "section": 1, "seat": 32 },
        { "id": 1024, "price": "", "row": 4, "section": 1, "seat": 33 },
        { "id": 1028, "price": "", "row": 4, "section": 1, "seat": 34 },
        { "id": 1038, "price": "", "row": 4, "section": 1, "seat": 35 },
        { "id": 1047, "price": "", "row": 4, "section": 1, "seat": 36 },
        { "id": 1058, "price": "", "row": 4, "section": 1, "seat": 37 },

        { "id": 949, "price": "", "row": 5, "section": 1, "seat": 28 },
        { "id": 953, "price": "", "row": 5, "section": 1, "seat": 29 },
        { "id": 959, "price": "", "row": 5, "section": 1, "seat": 30 },
        { "id": 963, "price": "", "row": 5, "section": 1, "seat": 31 },
        { "id": 967, "price": "", "row": 5, "section": 1, "seat": 32 },
        { "id": 971, "price": "", "row": 5, "section": 1, "seat": 33 },
        { "id": 978, "price": "", "row": 5, "section": 1, "seat": 34 },
        { "id": 985, "price": "", "row": 5, "section": 1, "seat": 35 },
        { "id": 989, "price": "", "row": 5, "section": 1, "seat": 36 },
        { "id": 999, "price": "", "row": 5, "section": 1, "seat": 37 },
        { "id": 1013, "price": "", "row": 5, "section": 1, "seat": 38 },

        { "id": 910, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 914, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 917, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 920, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 924, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 930, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 935, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 941, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 946, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 954, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 969, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 979, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 874, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 878, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 880, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 882, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 886, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 891, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 896, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 901, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 907, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 915, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 927, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 936, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 838, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 839, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 842, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 845, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 850, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 852, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 855, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 862, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 866, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 875, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 884, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 894, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 902, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 806, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 808, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 810, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 812, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 818, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 821, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 825, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 828, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 832, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 840, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 848, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 856, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 864, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 876, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 778, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 781, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 783, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 786, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 789, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 793, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 795, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 799, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 804, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 815, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 823, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 829, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 834, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 746, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 750, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 753, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 755, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 760, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 765, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 768, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 772, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 775, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 787, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 791, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 797, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 801, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 816, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 717, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 720, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 722, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 726, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 730, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 734, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 737, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 743, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 751, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 757, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 766, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 770, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 779, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 695, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 697, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 699, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 701, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 704, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 707, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 710, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 712, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 718, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 727, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 732, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 740, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 747, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 761, "price": "", "row": 13, "section": 1, "seat": 1 },
        { "id": 679, "price": "", "row": 14, "section": 1, "seat": 1 },
        { "id": 682, "price": "", "row": 14, "section": 1, "seat": 1 },
        { "id": 685, "price": "", "row": 14, "section": 1, "seat": 1 },

        { "id": 1177, "price": "", "row": 1, "section": 1, "seat": 28 },
        { "id": 1189, "price": "", "row": 1, "section": 1, "seat": 29 },
        { "id": 1194, "price": "", "row": 1, "section": 1, "seat": 30 },
        { "id": 1206, "price": "", "row": 1, "section": 1, "seat": 31 },
        { "id": 1216, "price": "", "row": 1, "section": 1, "seat": 32 },
        { "id": 1222, "price": "", "row": 1, "section": 1, "seat": 33 },

        { "id": 1140, "price": "", "row": 2, "section": 1, "seat": 32 },
        { "id": 1154, "price": "", "row": 2, "section": 1, "seat": 33 },
        { "id": 1163, "price": "", "row": 2, "section": 1, "seat": 34 },
        { "id": 1174, "price": "", "row": 2, "section": 1, "seat": 35 },
        { "id": 1183, "price": "", "row": 2, "section": 1, "seat": 36 },
        { "id": 1192, "price": "", "row": 2, "section": 1, "seat": 37 },
        { "id": 1204, "price": "", "row": 2, "section": 1, "seat": 38 },

        { "id": 1110, "price": "", "row": 3, "section": 1, "seat": 35 },
        { "id": 1119, "price": "", "row": 3, "section": 1, "seat": 36 },
        { "id": 1131, "price": "", "row": 3, "section": 1, "seat": 37 },
        { "id": 1139, "price": "", "row": 3, "section": 1, "seat": 38 },
        { "id": 1144, "price": "", "row": 3, "section": 1, "seat": 39 },
        { "id": 1156, "price": "", "row": 3, "section": 1, "seat": 40 },
        { "id": 1172, "price": "", "row": 3, "section": 1, "seat": 41 },
        { "id": 1184, "price": "", "row": 3, "section": 1, "seat": 42 },

        { "id": 1076, "price": "", "row": 4, "section": 1, "seat": 38 },
        { "id": 1088, "price": "", "row": 4, "section": 1, "seat": 39 },
        { "id": 1101, "price": "", "row": 4, "section": 1, "seat": 40 },
        { "id": 1113, "price": "", "row": 4, "section": 1, "seat": 41 },
        { "id": 1127, "price": "", "row": 4, "section": 1, "seat": 42 },
        { "id": 1145, "price": "", "row": 4, "section": 1, "seat": 43 },
        { "id": 1160, "price": "", "row": 4, "section": 1, "seat": 44 },
        { "id": 1033, "price": "", "row": 5, "section": 1, "seat": 39 },
        { "id": 1048, "price": "", "row": 5, "section": 1, "seat": 40 },
        { "id": 1060, "price": "", "row": 5, "section": 1, "seat": 41 },

        { "id": 1070, "price": "", "row": 5, "section": 1, "seat": 42 },
        { "id": 1081, "price": "", "row": 5, "section": 1, "seat": 43 },
        { "id": 1102, "price": "", "row": 5, "section": 1, "seat": 44 },
        { "id": 1117, "price": "", "row": 5, "section": 1, "seat": 45 },
        { "id": 1132, "price": "", "row": 5, "section": 1, "seat": 46 },
        { "id": 1004, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1020, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1029, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1042, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1064, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1074, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1094, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 1111, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 960, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 973, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 987, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1000, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1021, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1034, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1054, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1068, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 1082, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 925, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 937, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 947, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 965, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 983, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 992, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 1014, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 1030, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 898, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 911, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 931, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 943, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 961, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 980, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 993, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 1022, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 1036, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 860, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 869, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 888, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 904, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 921, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 939, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 955, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 981, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 846, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 858, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 870, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 892, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 905, "price": "", "row": 11, "section": 1, "seat": 1 },
        { "id": 819, "price": "", "row": 12, "section": 1, "seat": 1 },
        { "id": 773, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 762, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 741, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 723, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 708, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 693, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 689, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 677, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 670, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 660, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 648, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 632, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 617, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 604, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 590, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 573, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 735, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 714, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 702, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 691, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 680, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 669, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 655, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 641, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 618, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 603, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 589, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 571, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 559, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 541, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 531, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 687, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 675, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 672, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 667, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 661, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 657, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 652, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 646, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 644, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 638, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 633, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 628, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 626, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 623, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 665, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 656, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 649, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 642, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 630, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 620, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 614, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 609, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 606, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 597, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 593, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 591, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 584, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 580, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 636, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 619, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 612, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 605, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 595, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 579, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 577, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 569, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 566, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 560, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 556, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 552, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 547, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 544, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 542, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 599, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 583, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 574, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 565, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 555, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 546, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 537, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 533, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 527, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 528, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 518, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 514, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 512, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 508, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 504, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 563, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 551, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 539, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 532, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 524, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 516, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 507, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 502, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 496, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 494, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 488, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 486, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 482, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 478, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 475, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 472, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 529, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 520, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 506, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 499, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 492, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 484, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 474, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 468, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 464, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 458, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 455, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 451, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 447, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 444, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 442, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 437, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 598, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 498, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 490, "price": "", "row": 7, "section": 1, "seat": 1 },

        { "id": 480, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 467, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 462, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 454, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 446, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 436, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 432, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 426, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 422, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 419, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 415, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 412, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 406, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 402, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 400, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 466, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 460, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 450, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 435, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 430, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 424, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 414, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 405, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 398, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 393, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 388, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 383, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 380, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 374, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 369, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 366, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 364, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 434, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 428, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 418, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 404, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 395, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 387, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 379, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 368, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 360, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 358, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 351, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 347, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 344, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 340, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 335, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 332, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 328, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 410, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 394, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 385, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 373, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 362, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 355, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 346, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 339, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 327, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 322, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 320, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 316, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 312, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 308, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 304, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 302, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 300, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 296, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 624, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 627, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 629, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 634, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 639, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 645, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 647, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 653, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 658, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 662, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 668, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 673, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 676, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 581, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 585, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 592, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 594, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 598, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 607, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 610, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 615, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 621, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 631, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 643, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 650, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 659, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 666, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 543, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 545, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 548, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 553, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 557, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 561, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 567, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 570, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 578, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 582, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 596, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 608, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 613, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 622, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 637, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 505, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 509, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 513, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 515, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 519, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 523, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 528, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 534, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 538, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 549, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 558, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 568, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 575, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 586, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 600, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 473, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 476, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 479, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 483, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 487, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 489, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 495, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 497, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 503, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 510, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 517, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 525, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 535, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 540, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 554, "price": "", "row": 5, "section": 1, "seat": 1 },

        { "id": 545, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 564, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 538, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 438, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 443, "price": "", "row": 6, "section": 1, "seat": 1 },

        { "id": 445, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 448, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 452, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 456, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 459, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 465, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 469, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 477, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 485, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 493, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 500, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 511, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 521, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 530, "price": "", "row": 6, "section": 1, "seat": 1 },
        { "id": 401, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 403, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 407, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 443, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 416, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 420, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 423, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 427, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 433, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 439, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 449, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 457, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 463, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 470, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 481, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 491, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 501, "price": "", "row": 7, "section": 1, "seat": 1 },
        { "id": 365, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 367, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 370, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 375, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 381, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 384, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 389, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 392, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 399, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 408, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 417, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 425, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 431, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 440, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 453, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 461, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 471, "price": "", "row": 8, "section": 1, "seat": 1 },
        { "id": 329, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 333, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 336, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 341, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 345, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 348, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 352, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 358, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 359, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 361, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 371, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 382, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 390, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 396, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 409, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 421, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 429, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 441, "price": "", "row": 9, "section": 1, "seat": 1 },
        { "id": 297, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 301, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 303, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 305, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 309, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 313, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 317, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 321, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 323, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 330, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 342, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 349, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 356, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 363, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 376, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 386, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 397, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 411, "price": "", "row": 10, "section": 1, "seat": 1 },
        { "id": 576, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 587, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 601, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 611, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 625, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 640, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 654, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 663, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 671, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 683, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 688, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 692, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 705, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 713, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 728, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 738, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 526, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 536, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 550, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 562, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 572, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 588, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 602, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 616, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 635, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 651, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 664, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 674, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 686, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 690, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 281, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 272, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 263, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 254, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 246, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 357, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 338, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 318, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 299, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 288, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 279, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 269, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 259, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 250, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 243, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 235, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 378, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 354, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 334, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 314, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 294, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 285, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 275, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 265, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 253, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 244, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 236, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 326, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 311, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 292, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 284, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 271, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 262, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 249, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 240, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 372, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 350, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 324, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 306, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 290, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 278, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 267, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 257, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 247, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 238, "price": "", "row": 5, "section": 1, "seat": 1 },
        { "id": 223, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 219, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 214, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 207, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 198, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 192, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 185, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 179, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 170, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 221, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 218, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 212, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 204, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 196, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 188, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 180, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 172, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 164, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 225, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 220, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 216, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 209, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 201, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 191, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 182, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 175, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 166, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 159, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 222, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 217, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 210, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 202, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 194, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 186, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 176, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 168, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 161, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 155, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 153, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 150, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 146, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 141, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 135, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 130, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 124, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 117, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 110, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 184, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 144, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 139, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 133, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 126, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 116, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 108, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 101, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 96, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 143, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 138, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 131, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 122, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 115, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 106, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 99, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 90, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 82, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 71, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 137, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 129, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 120, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 112, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 103, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 93, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 85, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 75, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 61, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 53, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 95, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 91, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 86, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 80, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 78, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 72, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 69, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 66, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 65, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 77, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 68, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 57, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 55, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 51, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 48, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 45, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 41, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 39, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 50, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 43, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 34, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 32, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 29, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 27, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 24, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 21, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 18, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 31, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 26, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 20, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 14, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 12, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 10, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 8, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 6, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 4, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 2, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 59, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 60, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 62, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 67, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 70, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 73, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 79, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 81, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 87, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 36, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 38, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 40, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 42, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 46, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 49, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 52, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 56, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 58, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 16, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 17, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 19, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 22, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 25, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 28, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 30, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 33, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 35, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 44, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 0, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 1, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 3, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 5, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 7, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 9, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 11, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 13, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 15, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 23, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 100, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 105, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 111, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 118, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 125, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 128, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 136, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 142, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 147, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 84, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 89, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 97, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 102, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 109, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 119, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 127, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 134, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 140, "price": "", "row": 2, "section": 1, "seat": 1 },
        { "id": 63, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 74, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 83, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 92, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 98, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 107, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 114, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 123, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 132, "price": "", "row": 3, "section": 1, "seat": 1 },
        { "id": 37, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 47, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 54, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 64, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 76, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 88, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 94, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 104, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 113, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 121, "price": "", "row": 4, "section": 1, "seat": 1 },
        { "id": 157, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 163, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 171, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 177, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 184, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 193, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 199, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 206, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 215, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 152, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 158, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 165, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 173, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 181, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 189, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 197, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 205, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 213, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 149, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 154, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 160, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 167, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 174, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 183, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 190, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 200, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 208, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 145, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 151, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 156, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 162, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 169, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 178, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 187, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 195, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 203, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 211, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 289, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 282, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 273, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 264, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 255, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 319, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 298, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 287, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 277, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 270, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 260, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 251, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 242, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 234, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 230, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 226, "price": "", "row": 2, "section": 1, "seat": 2 },
        { "id": 331, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 310, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 298, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 283, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 274, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 261, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 252, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 241, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 233, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 229, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 224, "price": "", "row": 4, "section": 1, "seat": 4 },
        { "id": 325, "price": "", "row": 5, "section": 1, "seat": 5 },
        { "id": 307, "price": "", "row": 5, "section": 1, "seat": 5 },
        { "id": 291, "price": "", "row": 5, "section": 1, "seat": 5 },
        { "id": 280, "price": "", "row": 5, "section": 1, "seat": 5 },
        { "id": 268, "price": "", "row": 5, "section": 1, "seat": 5 },
        { "id": 258, "price": "", "row": 5, "section": 1, "seat": 5 },
        { "id": 248, "price": "", "row": 5, "section": 1, "seat": 5 },
        { "id": 239, "price": "", "row": 5, "section": 1, "seat": 5 },
        { "id": 232, "price": "", "row": 5, "section": 1, "seat": 5 },
        { "id": 228, "price": "", "row": 5, "section": 1, "seat": 5 },
        { "id": 1274, "price": "", "row": 1, "section": 1, "seat": 37 },
        { "id": 1264, "price": "", "row": 1, "section": 1, "seat": 36 },
        { "id": 1252, "price": "", "row": 1, "section": 1, "seat": 35 },

        { "id": 1241, "price": "", "row": 1, "section": 1, "seat": 34 },
        { "id": 1277, "price": "", "row": 2, "section": 1, "seat": 44 },
        { "id": 1271, "price": "", "row": 2, "section": 1, "seat": 43 },
        { "id": 1261, "price": "", "row": 2, "section": 1, "seat": 42 },
        { "id": 1250, "price": "", "row": 2, "section": 1, "seat": 41 },
        { "id": 1236, "price": "", "row": 2, "section": 1, "seat": 40 },
        { "id": 1224, "price": "", "row": 2, "section": 1, "seat": 39 },
        { "id": 1208, "price": "", "row": 3, "section": 1, "seat": 43 },
        { "id": 1220, "price": "", "row": 3, "section": 1, "seat": 44 },
        { "id": 1233, "price": "", "row": 3, "section": 1, "seat": 45 },
        { "id": 1245, "price": "", "row": 3, "section": 1, "seat": 46 },

        { "id": 1258, "price": "", "row": 3, "section": 1, "seat": 47 },
        { "id": 1268, "price": "", "row": 3, "section": 1, "seat": 48 },

        { "id": 1190, "price": "", "row": 4, "section": 1, "seat": 45 },
        { "id": 1202, "price": "", "row": 4, "section": 1, "seat": 46 },
        { "id": 1217, "price": "", "row": 4, "section": 1, "seat": 47 },
        { "id": 1229, "price": "", "row": 4, "section": 1, "seat": 48 },
        { "id": 1242, "price": "", "row": 4, "section": 1, "seat": 49 },
        { "id": 1255, "price": "", "row": 4, "section": 1, "seat": 50 },
        { "id": 1269, "price": "", "row": 4, "section": 1, "seat": 51 },

        { "id": 1170, "price": "", "row": 5, "section": 1, "seat": 47 },
        { "id": 1185, "price": "", "row": 5, "section": 1, "seat": 48 },
        { "id": 1198, "price": "", "row": 5, "section": 1, "seat": 49 },
        { "id": 1211, "price": "", "row": 5, "section": 1, "seat": 50 },
        { "id": 1226, "price": "", "row": 5, "section": 1, "seat": 51 },
        { "id": 1238, "price": "", "row": 5, "section": 1, "seat": 52 },
        { "id": 1256, "price": "", "row": 5, "section": 1, "seat": 53 },

        { "id": 1150, "price": "", "row": 6, "section": 1, "seat": 6 },
        { "id": 1168, "price": "", "row": 6, "section": 1, "seat": 6 },
        { "id": 1186, "price": "", "row": 6, "section": 1, "seat": 6 },
        { "id": 1199, "price": "", "row": 6, "section": 1, "seat": 6 },
        { "id": 1212, "price": "", "row": 6, "section": 1, "seat": 6 },
        { "id": 1230, "price": "", "row": 6, "section": 1, "seat": 6 },
        { "id": 1246, "price": "", "row": 6, "section": 1, "seat": 6 },
        { "id": 1262, "price": "", "row": 6, "section": 1, "seat": 6 },
        { "id": 1123, "price": "", "row": 7, "section": 1, "seat": 7 },
        { "id": 1146, "price": "", "row": 7, "section": 1, "seat": 7 },
        { "id": 1164, "price": "", "row": 7, "section": 1, "seat": 7 },
        { "id": 1178, "price": "", "row": 7, "section": 1, "seat": 7 },
        { "id": 1200, "price": "", "row": 7, "section": 1, "seat": 7 },
        { "id": 1218, "price": "", "row": 7, "section": 1, "seat": 7 },
        { "id": 1232, "price": "", "row": 7, "section": 1, "seat": 7 },
        { "id": 1248, "price": "", "row": 7, "section": 1, "seat": 7 },
        { "id": 337, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 315, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 295, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 286, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 276, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 266, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 256, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 245, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 237, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 231, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 227, "price": "", "row": 3, "section": 1, "seat": 3 },
        { "id": 1105, "price": "", "row": 8, "section": 1, "seat": 9 },
        { "id": 1124, "price": "", "row": 8, "section": 1, "seat": 9 },
        { "id": 1273, "price": "", "row": 1, "section": 1, "seat": 1 },
        { "id": 1263, "price": "", "row": 1, "section": 1, "seat": 2 },
        { "id": 1251, "price": "", "row": 1, "section": 1, "seat": 3 },
        { "id": 1240, "price": "", "row": 1, "section": 1, "seat": 4 },




























    ])


    const getPrice = (y, i, x) => {
        console.log(i)
        setPosition({ x, y })
        let row = null
        let seat = 0
        let price = null
        let item = seansArr.find((elm) => elm.id === i)
        console.log(i)
        price = 0
        setActiveTicket({
            row: item?.row,
            price: item?.price,
            bench: item?.seat,
            id: i
        })
        setShowModal(true)
    }

    const addTicket = (i) => {
        let data = [...coordinatesState]
        data[i].active = !data[i].active
        if (data[i].active) {
            dispatch(SetTicketsAction(activeTicket))
        }
        else {
            dispatch(RemoveTicketsAction(activeTicket))
        }
        setCoordinatesState(data)
    }

    useEffect(() => {
        const image = new Image()
        image.src = require('../../assets/AramKhachatryan.png')

        image.onload = () => {
            const canvas = document.createElement('canvas')
            canvas.width = image.width
            canvas.height = image.height
            const ctx = canvas.getContext('2d')
            ctx.drawImage(image, 0, 0, image.width, image.height)

            const imageData = ctx.getImageData(0, 0, image.width, image.height)
            const pixelData = imageData.data
            const coordinates = []

            for (let y = 0; y < image.height; y++) {
                for (let x = 0; x < image.width; x++) {
                    const offset = (y * image.width + x) * 4
                    const r = pixelData[offset]
                    const g = pixelData[offset + 1]
                    const b = pixelData[offset + 2]

                    if (r >= 100 && g <= 35 && b <= 35) {
                        coordinates.push({ x, y, active: false, id: coordinates.length })
                    }
                }
            }
            console.log(coordinates.length)
            setCoordinatesState(coordinates)
        };
    }, []);


    return (

        <div className='hallWrapper'>

            <div className='hall' >
                <div >
                    <img alt='' src={require('../../assets/AramKhachatryan.png')} />
                    {coordinatesState.map((e, i) => {
                        // if (seansArr[2040 - i].price)
                        return <button
                            key={i}
                            onMouseOver={() => {
                                getPrice(e.y, i, e.x)
                                setActiveButton(i)
                            }}
                            style={
                                {
                                    top: e?.y - 4,
                                    left: e?.x - 4,
                                    backgroundColor: e.active && 'green'
                                }
                            }
                            id='seatStyle'
                            className={[
                                i == activeButton ? 'activeButton' : '',
                                e.active ? "addTicketButton" : '']}
                            onMouseLeave={() => {
                                setShowModal(false)
                                setActiveButton(null)
                            }}
                            onClick={() => addTicket(i)}
                        />
                    })}

                    {showModal &&
                        <div style={{ top: position.y, left: position.x, position: 'absolute' }} className='parter'>
                            <p className='Teatertext'>շարք {activeTicket.row}</p>
                            <p className='Teatertext'>տեղ {activeTicket.bench}</p>
                            <p className='Teatertext'>դրամ {activeTicket.price}</p>
                        </div>
                    }
                </div>
            </div>
        </div>
    )
}
export default AramKhachatryan
